### ISSUE TITLE
NullPointerException at FlowTool.java:276

### ISSUE THREAD

**Issue by mvsoder** [avereon/aveon#1]
java.lang.NullPointerException
	at com.avereon.aveon@1.0-SNAPSHOT/com.avereon.aveon.FlowTool.setStrokeWidth(FlowTool.java:276)
	at com.avereon.aveon@1.0-SNAPSHOT/com.avereon.aveon.FlowTool.generateGrid(FlowTool.java:259)
	at com.avereon.aveon@1.0-SNAPSHOT/com.avereon.aveon.FlowTool.setAirfoil(FlowTool.java:185)
	at com.avereon.aveon@1.0-SNAPSHOT/com.avereon.aveon.FlowTool.lambda$loadAirfoilPoints$2(FlowTool.java:285)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by mvsoder** [comment]
This is likely due to the window not being available when the tool is being restored. Probably because Tool.assetReady() was called before the tool was added to the workarea. Might need to reconsider and rework tool and asset readiness.
